accounts/urls.py
from xml.dom.minidom import Document
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('registro/', views.registro, name='registro'),  
]
  

core/urls.py
from xml.dom.minidom import Document
from django.urls import path , include
from tienda import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.db import router 
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('tienda.urls')),
    path('shop/', include('shopping.urls')),
    path('auth/', include('accounts.urls')),
    path('accounts/' , include('django.contrib.auth.urls') , name = 'login'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tienda/urls.py
from xml.dom.minidom import Document
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static
from django.db import router
from tienda import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register("producto", views.ProductoViewSet)

app_name = 'tienda'

urlpatterns = [
    path('store', views.store, name='store'),
    path('Contacto', views.contacto, name='contacto'),
    path('api/', include(router.urls)),
    path('detalle/<id>', views.detalleProducto, name='detalle'),
    path('listar/', views.listarProductos, name='listar'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('producto/<int:product_id>/modificar/', views.modificar, name='modificar'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
]
  

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid m-0.5">
    <a class="navbar-brand" target="_blank" href="{% url 'accounts:registro'%}">A R I Z O N A &nbsp;||</a>
    {% if user.is_authenticated %}
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><s>@{{user.username}}...&nbsp;</s></a>
    {% endif %}
    &nbsp;
    <a class="nav-link pl-3" aria-current="page" href="{% url 'home'%}"> H O M E </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tienda:store'%}">Tienda</a>
        </li>
        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tienda:addproducto'%}">Agregar Producto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tienda:listar'%}">Listado de Producto</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
        </li>
        {% elif user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link " aria-current="page" href="{% url 'home'%}">Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:registro' %}">Regístrate</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tienda:contacto' %}">Contacto</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" id="cart-button" style="cursor: pointer;">Carrito</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="cart-button">
            {% if total_productos_carrito > 0 %}
            <span class="carrito-icon">&#128722;</span>
            <span class="carrito-num">{{ total_productos_carrito }}</span>
            {% endif %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">ARZNA</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/footer.html
<footer class="text-center text-white" style="background-color: #f1f1f1;">
    <!-- Grid container -->
    <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
                data-mdb-ripple-color="dark"><i class="fab fa-facebook-f"></i></a>

            <!-- Twitter -->
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
                data-mdb-ripple-color="dark"><i class="fab fa-twitter"></i></a>

            <!-- Google -->
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
                data-mdb-ripple-color="dark"><i class="fab fa-google"></i></a>

            <!-- Instagram -->
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
                data-mdb-ripple-color="dark"><i class="fab fa-instagram"></i></a>

            <!-- Linkedin -->
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
                data-mdb-ripple-color="dark"><i class="fab fa-linkedin"></i></a>
            <!-- Github -->
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
                data-mdb-ripple-color="dark"><i class="fab fa-github"></i></a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2050 Copyright:
        <a class="text-dark" href="#">A R I Z O N A</a>
    </div>
    <!-- Copyright -->
</footer>

<style>
    footer {
        position: absolute;
        bottom: -125px;
        width: 100%;
    }
</style>