core/urls.py
from xml.dom.minidom import Document
from django.urls import path , include
from tienda import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.db import router 
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('tienda.urls')),
    path('shop/', include('shopping.urls')),
    path('auth/', include('accounts.urls')),
    path('accounts/' , include('django.contrib.auth.urls') , name = 'login'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tienda/urls.py
from xml.dom.minidom import Document
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static
from django.db import router
from tienda import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register("producto", views.ProductoViewSet)

app_name = 'tienda'

urlpatterns = [
    path('store', views.store, name='store'),
    path('Contacto', views.contacto, name='contacto'),
    path('api/', include(router.urls)),
    path('detalle/<id>', views.detalleProducto, name='detalle'),
    path('listar/', views.listarProductos, name='listar'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('producto/<int:product_id>/modificar/', views.modificar, name='modificar'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
]
  

tienda/models.py
from distutils.command import upload
from pyexpat import model
from django.db import models


class Categorias(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    

class Marca(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre

class Producto(models.Model):

    OFERTA_CHOICES = [
        ('0', 'Sin oferta'),
        ('5', '5% de descuento'),
        ('10', '10% de descuento'),
        ('15', '15% de descuento'),
        ('20', '20% de descuento'),
        ('25', '25% de descuento'),
        ('30', '30% de descuento'),
        ('35', '35% de descuento'),
        ('40', '40% de descuento'),
        ('45', '45% de descuento'),
        ('50', '50% de descuento'),
    ]

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    precio = models.IntegerField()
    descripcion = models.TextField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    categoria = models.ForeignKey(Categorias, on_delete=models.PROTECT)
    stock = models.IntegerField(null=True, default=0)
    oferta = models.CharField(max_length=2, choices=OFERTA_CHOICES, default='0')
    nuevo = models.BooleanField()
    imagen = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)
    
    @property
    def precio_descuento(self):
        descuento = int(self.oferta) # Convertir la cadena a entero
        precio_descuento = self.precio - ((descuento / 100) * self.precio) # Calcular el descuento
        return precio_descuento

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'productos'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class contacto(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()
    numero = models.CharField(max_length=12)
    descripcion = models.TextField(max_length=150)
    region = models.CharField(max_length=50)
    comuna = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre




    

tienda/forms.py
from tkinter import Widget
from django import forms
from .models import contacto,Producto
import re
from django.contrib.auth.forms import UserCreationForm  
from accounts.models import User


class ContactoForm(forms.ModelForm):
    class Meta:
        model = contacto
        fields = ["nombre", "apellido", "email", "numero", "descripcion", "region", "comuna"]
        widgets = {
            "descripcion": forms.Textarea(attrs={"cols": 37, "rows": 5}),
            "region": forms.Select(attrs={"id": "region"}),
            "comuna": forms.Select(attrs={"id": "comuna"}),
        }



class ProductoForm(forms.ModelForm):
    class Meta:

        model = Producto
        widgets = {
            'descripcion': forms.Textarea(attrs={'cols': 37, 'rows': 5 }),
        }
        fields = '__all__'

tienda/views.py
from email import message
from django.forms import PasswordInput
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
import random
from tienda.models import Categorias, Marca, Producto
from .forms import ContactoForm,ProductoForm
from django.contrib import messages
from django.http import Http404
import json

from .serializers import productoSerializer
from rest_framework import viewsets
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from decorators import admin_required,client_required

from shopping.carrito import Carrito


class ProductoViewSet(viewsets.ModelViewSet):
    queryset =Producto.objects.all()
    serializer_class = productoSerializer


def home(request):
    return render(request, 'home.html', {'name': 'gvrrido'})


def store(request):
    carrito = Carrito(request)
    busqueda = request.POST.get("buscador")
    print(f"Valor de búsqueda: {busqueda}")  # Impresión para depuración
    productos = Producto.objects.order_by('nombre')
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__startswith=busqueda) |
            Q(precio__icontains=busqueda)
        ).order_by('nombre').distinct()
    data = {
        'entity': productos,
        'title': 'LISTADO DE PRODUCTOS',
        'total_productos_carrito': carrito.cantidad_total()
    }
    return render(request, 'store.html', data)



def contacto(request):
    with open('resource/regiones-comunas.json', encoding='utf-8') as f:
        try:
            rc = json.load(f)
            print(rc)
        except ValueError:
            print("El archivo JSON está mal formateado")
    regiones = [(r['name']) for r in rc['regions']]
    comunas = {r['name']: r['communes'] for r in rc['regions']}
    form = ContactoForm()
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            print("mensaje exitoso")
            form = ContactoForm()  # Crear una nueva instancia del formulario vacío
        else:
            form = formulario  # Asignar el formulario no válido a la variable 'form'     
    return render(request, 'contacto.html', {'form': form, 'regiones': regiones, 'comunas': comunas})


def detalleProducto(request,id):
    producto = get_object_or_404(Producto,id=id)
    context = {
        'producto': producto
    }
    return render(request, 'producto/detalle.html', context )


def addProducto(request):
    data = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/listar")
        else:
            data["form"] = formulario   
    return render(request, 'producto/agregar.html', data)


def listarProductos(request):
    busqueda = request.POST.get("buscador")
    lista_productos = Producto.objects.order_by('nombre')
    if busqueda:
        lista_productos = Producto.objects.filter(
            Q(nombre__startswith=busqueda) |
            Q(precio__icontains=busqueda)
        ).order_by('nombre').distinct()
    try:
        lista_productos = lista_productos
    except:
        raise Http404

    data = {'entity': lista_productos,
            'title': 'LISTADO DE PRODUCTOS',
            }
    return render(request, 'producto/listar.html', data)




def modificar(request, product_id):
    producto = get_object_or_404(Producto, id=product_id)

    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'producto/modificar.html', {'form': form})




def eliminar_producto(request, product_id):
    producto = get_object_or_404(Producto, id=product_id)
    producto.delete()
    return redirect('tienda:listar')

tienda/templates/producto/agregar.html
{% extends 'layout.html' %}
{% block content %}


<body class="body">
  <br>
  <br>
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
          {% if title %}
          <h1 class="titulo-form mb-4 text-center">{{ title }}</h1>
          {% endif %}
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="botones mt-4 d-flex justify-content-center">
              <a href="{% url 'tienda:listar'%}" class="btn btn-outline-secondary me-2">Cancelar</a>
              <button type="submit" class="btn btn-primary" aria-label="Registrar">Registrar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br>
  <style>
    .titulo-form {
      color: #3B3B3B;
      font-size: 2.5rem;
      font-weight: bold;
    }

    form {
      margin-top: 1rem;
    }

    .form-group {
      margin-bottom: 1rem;
    }

    label {
      font-weight: bold;
    }

    input[type="text"],
    input[type="number"],
    input[type="file"],
    select,
    textarea {
      padding: 0.5rem;
      border: 1px solid #CED4DA;
      border-radius: 0.25rem;
      width: 100%;
    }

    input[type="text"]:focus,
    input[type="number"]:focus,
    input[type="checkbox"]:focus,
    input[type="file"]:focus,
    select:focus,
    textarea:focus {
      outline: none;
      box-shadow: 0 0 0 0.25rem rgba(0, 123, 255, 0.25);
    }

    .form-text {
      font-size: 0.875rem;
    }

    .botones {
      align-items: center;
    }

    .btn {
      margin-right: 0.5rem;
    }

    /* Estilos específicos para pantallas pequeñas */
    @media screen and (max-width: 576px) {
      .titulo-form {
        font-size: 2rem;
      }

      .botones {
        flex-direction: column;
      }

      .btn {
        width: 100%;
        margin-top: 0.5rem;
        margin-right: 0;
      }
    }
  </style>
{% endblock %}

tienda/templates/producto/detalle.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<style>
    .btn {
        background-color: rgb(10, 10, 10);
        color: aliceblue;
        width: 120px;

    }

    .btn:hover {
        background-color: #FF5E5E;
    }
</style>
<div class="containe m-5">
    <div class="card">
        <div class="card-body">
            <div class="row gx-4 gx-lg-5 align-items-center">
                {% if producto.imagen %}
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ producto.imagen.url }}" />
                </div>
                {% else %}
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                        src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." /></div>
                {% endif %}
                <div class="col-md-6">
                    <div class="small mb-1">Código:000-{{ producto.id }}</div>
                    <h1 class="display-5 fw-bolder">{{ producto.nombre }}</h1>
                    <span> Marca: <b>{{ producto.marca }}</b></span><br>
                    <br>
                    <p>desc.<br>{{ producto.descripcion }}</p>
                    <div class="fs-5 mb-5">
                        <a href="{% url 'tienda:store'%}" class="btn">Store</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

tienda/templates/producto/listar.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

{% block head %}
<LINK REL=StyleSheet HREF='{% static 'css/list.css' %}' TYPE="text/css">
{% endblock %}


<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body table-responsive align-items-center">
                        <!-- inline-block justify-content-end mb-2 mx-2 -->
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <a href="{% url 'tienda:addproducto' %}" class="btn btn-outline-primary" type="submit">
                                    Nuevo
                                    Producto</a>
                            </div>

                            <form class="  form-inline" method="POST" action="">
                                {% csrf_token %}
                                <div class="input-group buscador">
                                    <input type="text" class="form-control bg-light border-1 small text-center"
                                        name="buscador" placeholder="buscar..." value="{{ request.POST.buscador }}" />
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-outline-primary">buscar</button>
                                        &nbsp;
                                        <a href="{% url 'tienda:listar'%}" class="btn btn-outline-primary">TODO</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <br>
                        <table class="table table-condensed">
                            <thead class="thead-dark text-center ">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">nombre</th>
                                    <th scope="col">precio</th>
                                    <th scope="col">categoria</th>
                                    <th scope="col">marca</th>
                                    <th scope="col">oferta</th>
                                    <th scope="col">stock</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                {% load bootstrap_icons %} {% if entity %} {% for producto in entity %}
                                <tr {% if producto.stock == 0 %}style="background-color: rgba(255,0,0,0.2);" {% endif %}>
                                    <td>{{ producto.id }}</td>
                                    <td>{{ producto.nombre }}</td>
                                    <td>{{ producto.precio }}</td>
                                    <td>{{ producto.categoria }}</td>
                                    <td>{{ producto.marca }}</td>
                                    {% if producto.oferta != '0' %}
                                    <td>-{{ producto.oferta }}%</td>
                                    {% else %}
                                    <td>sin oferta</td>
                                    {% endif %}
                                    <td>{{ producto.stock }}</td>
                                    <td colspan="2">
                                        <div class="btn-group d-flex justify-content-center" role="group"
                                            aria-label="Acciones">
                                            <a class="btn btn-secondary btn-sm"
                                                href="{% url 'tienda:modificar' product_id=producto.id %}">
                                                <i class="bi bi-pencil-square"></i> Modificar
                                            </a>
                                            &nbsp;
                                            <a class="btn btn-danger btn-sm"
                                                href="{% url 'tienda:eliminar' producto.id %}">
                                                <i class="bi bi-trash-fill"></i> Eliminar
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No se encontraron Productos!!</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tienda/templates/producto/modificar.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

{% block head %}
<LINK REL=StyleSheet HREF='{% static 'css/update.css' %}' TYPE="text/css">
{% endblock %}

  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12">
        <div class="card shadow-sm">
          <div class="card-body">
            <h1 class="h3 mb-4 text-center titulo-form">Modificando producto</h1>
            <form action="" method="post" class="form">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="d-flex justify-content-end mt-4">
                <a href="{% url 'tienda:listar'%}" class="btn btn-outline-secondary me-2">Cancelar</a>
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}