core/urls.py
from xml.dom.minidom import Document
from django.urls import path , include
from tienda import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.db import router 
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('tienda.urls')),
    path('shop/', include('shopping.urls')),
    path('auth/', include('accounts.urls')),
    path('accounts/' , include('django.contrib.auth.urls') , name = 'login'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from shopping import views

app_name = 'shopping'

urlpatterns = [
    path('caja/', TemplateView.as_view(template_name='compra.html'), name='caja'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name="Add"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="Del"),
    path('restar/<int:producto_id>/', views.restar_producto, name="Sub"),
    path('limpiar/', views.limpiar_carrito, name="Cls"),
    path('compra/', views.procesar_compra, name="procesar_compra"),
]

tienda/urls.py
from xml.dom.minidom import Document
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static
from django.db import router
from tienda import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register("producto", views.ProductoViewSet)

app_name = 'tienda'

urlpatterns = [
    path('store', views.store, name='store'),
    path('Contacto', views.contacto, name='contacto'),
    path('api/', include(router.urls)),
    path('detalle/<id>', views.detalleProducto, name='detalle'),
    path('listar/', views.listarProductos, name='listar'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('producto/<int:product_id>/modificar/', views.modificar, name='modificar'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
]
  

tienda/models.py
from distutils.command import upload
from pyexpat import model
from django.db import models


class Categorias(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    

class Marca(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre

class Producto(models.Model):

    OFERTA_CHOICES = [
        ('0', 'Sin oferta'),
        ('5', '5% de descuento'),
        ('10', '10% de descuento'),
        ('15', '15% de descuento'),
        ('20', '20% de descuento'),
        ('25', '25% de descuento'),
        ('30', '30% de descuento'),
        ('35', '35% de descuento'),
        ('40', '40% de descuento'),
        ('45', '45% de descuento'),
        ('50', '50% de descuento'),
    ]

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    precio = models.IntegerField()
    descripcion = models.TextField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    categoria = models.ForeignKey(Categorias, on_delete=models.PROTECT)
    stock = models.IntegerField(null=True, default=0)
    oferta = models.CharField(max_length=2, choices=OFERTA_CHOICES, default='0')
    nuevo = models.BooleanField()
    imagen = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)
    
    @property
    def precio_descuento(self):
        descuento = int(self.oferta) # Convertir la cadena a entero
        precio_descuento = self.precio - ((descuento / 100) * self.precio) # Calcular el descuento
        return precio_descuento

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'productos'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class contacto(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()
    numero = models.CharField(max_length=12)
    descripcion = models.TextField(max_length=150)
    region = models.CharField(max_length=50)
    comuna = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre




    

tienda/forms.py
from tkinter import Widget
from django import forms
from .models import contacto,Producto
import re
from django.contrib.auth.forms import UserCreationForm  
from accounts.models import User


class ContactoForm(forms.ModelForm):
    class Meta:
        model = contacto
        fields = ["nombre", "apellido", "email", "numero", "descripcion", "region", "comuna"]
        widgets = {
            "descripcion": forms.Textarea(attrs={"cols": 37, "rows": 5}),
            "region": forms.Select(attrs={"id": "region"}),
            "comuna": forms.Select(attrs={"id": "comuna"}),
        }



class ProductoForm(forms.ModelForm):
    class Meta:

        model = Producto
        widgets = {
            'descripcion': forms.Textarea(attrs={'cols': 37, 'rows': 5 }),
        }
        fields = '__all__'

tienda/views.py
from email import message
from django.forms import PasswordInput
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
import random
from tienda.models import Categorias, Marca, Producto
from .forms import ContactoForm,ProductoForm
from django.contrib import messages
from django.http import Http404
import json

from .serializers import productoSerializer
from rest_framework import viewsets
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from decorators import admin_required,client_required

from shopping.carrito import Carrito


class ProductoViewSet(viewsets.ModelViewSet):
    queryset =Producto.objects.all()
    serializer_class = productoSerializer


def home(request):
    return render(request, 'home.html', {'name': 'gvrrido'})


def store(request):
    carrito = Carrito(request)
    busqueda = request.POST.get("buscador")
    print(f"Valor de búsqueda: {busqueda}")  # Impresión para depuración
    productos = Producto.objects.order_by('nombre')
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__startswith=busqueda) |
            Q(precio__icontains=busqueda)
        ).order_by('nombre').distinct()
    data = {
        'entity': productos,
        'title': 'LISTADO DE PRODUCTOS',
        'total_productos_carrito': carrito.cantidad_total()
    }
    return render(request, 'store.html', data)



def contacto(request):
    with open('resource/regiones-comunas.json', encoding='utf-8') as f:
        try:
            rc = json.load(f)
            print(rc)
        except ValueError:
            print("El archivo JSON está mal formateado")
    regiones = [(r['name']) for r in rc['regions']]
    comunas = {r['name']: r['communes'] for r in rc['regions']}
    form = ContactoForm()
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            print("mensaje exitoso")
            form = ContactoForm()  # Crear una nueva instancia del formulario vacío
        else:
            form = formulario  # Asignar el formulario no válido a la variable 'form'     
    return render(request, 'contacto.html', {'form': form, 'regiones': regiones, 'comunas': comunas})


def detalleProducto(request,id):
    producto = get_object_or_404(Producto,id=id)
    context = {
        'producto': producto
    }
    return render(request, 'producto/detalle.html', context )


def addProducto(request):
    data = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/listar")
        else:
            data["form"] = formulario   
    return render(request, 'producto/agregar.html', data)


def listarProductos(request):
    busqueda = request.POST.get("buscador")
    lista_productos = Producto.objects.order_by('nombre')
    if busqueda:
        lista_productos = Producto.objects.filter(
            Q(nombre__startswith=busqueda) |
            Q(precio__icontains=busqueda)
        ).order_by('nombre').distinct()
    try:
        lista_productos = lista_productos
    except:
        raise Http404

    data = {'entity': lista_productos,
            'title': 'LISTADO DE PRODUCTOS',
            }
    return render(request, 'producto/listar.html', data)




def modificar(request, product_id):
    producto = get_object_or_404(Producto, id=product_id)

    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'producto/modificar.html', {'form': form})




def eliminar_producto(request, product_id):
    producto = get_object_or_404(Producto, id=product_id)
    producto.delete()
    return redirect('tienda:listar')

tienda/templates/shop/carrito.html
<style>
    .quantity-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: -1em;
    }

    .btn-group {
        display: flex;
        align-items: center;
    }

    .btn-quantity {
        border: none;
        text-decoration: none;
        background-color: transparent;
        font-size: 20px;
        font-weight: bold;
        cursor: pointer;
        padding: 20px;
        color: black;
    }

    .btn-minus {
        font-size: 30px;
        padding-right: 5px;
    }

    .btn-quantity:hover {
        color: #555555;
    }
</style>
<div class="card">
    <div class="card-body">
        <h5 class="card-title text-center">CARRITO</h5>
        <div class="table-responsive">
            <table class="table table-borderless">
                <tbody>
                    {% if request.session.carrito %}
                    {% for key, value in request.session.carrito.items %}
                    <tr>
                        <td>
                            <div class="d-flex justify-content-between align-items-center">
                                <h3 class="mb-0">{{ value.nombre }}</h3>
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <span class="text-muted">OFERTA.</span>
                                {% if value.oferta != '0' %}
                                <span class="font-weight-bold" style="color: red;">-{{ value.oferta }}%</span>
                                {% else %}
                                <span class="font-weight-bold"> -------</span>
                                {% endif %}
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <span class="text-muted">PRECIO UNI.</span>
                                <span class="font-weight-bold">${{ value.precio_uni }}</span>
                            </div>
                            <div class="quantity-container">
                                <div class="btn-group">
                                    <span class="text-muted"id="value-cantidad">CANT. <b>({{ value.cantidad }})</b></span>
                                    <a href="{% url 'shopping:Add' value.producto_id %}"
                                        class="btn-quantity btn-plus">+</a>
                                    <span>|</span>
                                    <a href="{% url 'shopping:Sub' value.producto_id %}"
                                        class="btn-quantity btn-minus">-</a>
                                </div>
                                <span class="text-muted "><b>Sub-Total</b></span>
                                <span class="font-weight-bold">${{ value.acumulado|floatformat:0 }}</span>
                            </div>
                            <hr>
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>
                            <div class="alert alert-danger text-center">Sin Productos</div>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div class="row text-center mt-3">
            <div class="col-4">
                <a href="{% url 'shopping:Cls' %}" class="btn btn-dark">Limpiar</a>
            </div>
            <div class="col-8">
                <a href="{% url 'shopping:caja' %}" id="btn-guardar" class="btn btn-success">Realizar compra</a>
            </div>
        </div>
    </div>
</div>