core/urls.py
from xml.dom.minidom import Document
from django.urls import path , include
from tienda import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.db import router 
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('tienda.urls')),
    path('shop/', include('shopping.urls')),
    path('auth/', include('accounts.urls')),
    path('accounts/' , include('django.contrib.auth.urls') , name = 'login'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from shopping import views

app_name = 'shopping'

urlpatterns = [
    path('caja/', TemplateView.as_view(template_name='compra.html'), name='caja'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name="Add"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="Del"),
    path('restar/<int:producto_id>/', views.restar_producto, name="Sub"),
    path('limpiar/', views.limpiar_carrito, name="Cls"),
    path('compra/', views.procesar_compra, name="procesar_compra"),
]

shopping/models.py
from django.db import models

# Create your models here.

shopping/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse
from tienda.models import Categorias, Marca, Producto
from django.contrib import messages
from .carrito import Carrito


def compra(request):
    return render(request, 'compra.html')

def agregar_producto(request, producto_id):
    carrito = Carrito(request)
    return carrito.procesar_operacion(request, producto_id, 'agregar')

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    return carrito.procesar_operacion(request, producto_id, 'eliminar')

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    return carrito.procesar_operacion(request, producto_id, 'restar')



def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect(reverse("tienda:store"))


def procesar_compra(request):
    carrito = Carrito(request)
    for item in carrito.carrito.values():
        producto_id = item["producto_id"]
        cantidad = item["cantidad"]
        producto = Producto.objects.get(id=producto_id)
        producto.stock = max(producto.stock - cantidad, 0)
        producto.save()
    carrito.limpiar()
    return redirect(reverse("tienda:store"))

shopping/templates/compra.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

<div class="container">
  <h1 class="tienda-titulo">Realizar compra</h1>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Detalle de compra</h5>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Producto</th>
                <th>Precio unitario</th>
                <th>Cantidad</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {% if request.session.carrito %}
              {% for key, value in request.session.carrito.items %}
              <tr>
                <td>{{ value.nombre }}</td>
                <td>${{ value.precio_uni }}</td>
                <td>{{ value.cantidad }}</td>
                <td>${{ value.acumulado }}</td>
              </tr>
              {% endfor %}
              {% endif %}
              <tr>
                <td colspan="3" class="text-right"><strong>Total:</strong></td>
                <td>${{ total_carrito }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="text-right">
          <a href="{% url 'shopping:procesar_compra' %}" id="btn-guardar" class="btn btn-success">Comprar</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}